### PR TITLE
Feature/error handling 2 jb

### PR DESCRIPTION
**Pull request by JoshBennett793**
What I did:
- Improved styling and positioning of the error message. Previous error message would move elements around on the page when it rendered. 
  - I accomplished this using absolute positioning of the error message element relative to the form container.
- Separate header elements out into individual Header component to allow for Header specific elements and styling as we continue to iterate on the header
- Implemented a reducer function to abstract away the error message state setting functionality.
  - The reducer eliminates the reliance on multiple boolean flags and a large conditional to decide which error element to render. 
- Refactored the noDuplicates function to utilize the reduce method.

Did this break anything?

- [x] No
- [ ]  Yes

Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x]  Styling 
- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  Refactor(DRY-ing up/ reorganizing code, etc.)
- [ ]  Super small fix (Corrected a typo, removed a comment, etc.)
- [ ]  Skip all the other stuff and briefly explain the fix.

Checklist:

- [ ]  If this code needs to be tested, all tests are passing
- [x]  The code runs locally
- [ ]  There are comments where clarification/ organization is needed
- [x]  The code is DRY. If it's not, I tried my best
- [x]  I reviewed my code before pushing

What's next?
- Create a customized 404 page to be rendered.

### CODE REVIEW

**Review by Jwensloff — CHANGES_REQUESTED** [review]
I think implementing the useReducer messed with the search functionality

**Comment by JoshBennett793** [comment]
> I think implementing the useReducer messed with the search functionality

I've pulled and merged with main locally with no breaks to the search functionality.
- I merged Renee's changes to FavoriteContext.js and pushed those in to this PR. Reference: 82d4ddf

I've also opened the PR up in a GH codespace and it is working as expected.
I believe your local main may be different from remote main.

**Comment by JoshBennett793** [comment]
> > I think implementing the useReducer messed with the search functionality
> 
> I've pulled and merged with main locally with no breaks to the search functionality.
> 
> * I merged Renee's changes to FavoriteContext.js and pushed those in to this PR. Reference: [82d4ddf](https://github.com/Jwensloff/brew-buddy/commit/82d4ddf760b85cee890fd0fa76820e51da8f3633)
> 
> I've also opened the PR up in a GH codespace and it is working as expected. I believe your local main may be different from remote main.

The bug originated from the BreweryContext component in which I was attempting to use the array of params as the switch expression, causing unexpected behavior.
This bug has been resolved. Reference: [25b7aaf](https://github.com/Jwensloff/brew-buddy/pull/40/commits/25b7aaf0127e1c589e003eceed362a2ea12e6dd9)

**Comment by banjaminh** [comment]
All issues fixed! Nice work!

**Pull request merged**
